apiVersion: apps/v1
kind: Deployment
metadata:
  name:  notejam-deployment
  labels:
    app:  "notejam" #The name of the application 
spec:
  selector:
    matchLabels:
      app: notejam
  replicas: 3
  template:
    metadata:
      labels:
        app:  "notejam" #The name of the application 
    spec:
      containers:
      - name:  notejam
        image:  "azaksdev001.azurecr.io/python-notejam:03"
        env:
          - name: RDS_DB_NAME
            value: "notejam"
          - name: RDS_USERNAME
            value: "#########"
          - name: RDS_PASSWORD
            value: "#########"
          - name: RDS_HOSTNAME
            value: "#########"
          - name: RDS_PORT
            value: "3306"
        command:
          - "/start.sh"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8081
          name:  http
      restartPolicy: Always
      imagePullSecrets:
      - name: docker-registry